version: '3.8'

services:
  server:
    image: lavrushkoivan/web_chat
    ports:
      - 8080:8080
    depends_on:
      - chat_db
      - chat_static_db

  chat_db:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  chat_static_db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

volumes:
  postgres-db:
  chat_static_db:
