// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/chatroom": {
            "put": {
                "description": "Update an existing chatroom",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chatroom"
                ],
                "summary": "Update chatroom",
                "operationId": "update-chatroom",
                "parameters": [
                    {
                        "description": "Chatroom information",
                        "name": "chatroom",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Chatroom"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new chatroom",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chatroom"
                ],
                "summary": "Create chatroom",
                "operationId": "create-chatroom",
                "parameters": [
                    {
                        "description": "Chatroom information",
                        "name": "chatroom",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Chatroom"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete an existing chatroom",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chatroom"
                ],
                "summary": "Delete chatroom",
                "operationId": "delete-chatroom",
                "parameters": [
                    {
                        "description": "Chatroom deletion information",
                        "name": "DeleteChatDTO",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/delivery.DeleteChatDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/chatroom/{id}": {
            "get": {
                "description": "Get a chatroom by its ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chatroom"
                ],
                "summary": "Get chatroom by ID",
                "operationId": "get-chatroom-by-id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Chatroom ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/chatrooms/{limit}": {
            "get": {
                "description": "Get a list of chatrooms",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chatroom"
                ],
                "summary": "Get chatrooms",
                "operationId": "get-chatrooms",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Number of chatrooms to retrieve",
                        "name": "limit",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/user/enterChatroom": {
            "post": {
                "description": "Enter a chatroom",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chatroom"
                ],
                "summary": "Enter chatroom",
                "operationId": "enter-chatroom",
                "parameters": [
                    {
                        "description": "User chat information",
                        "name": "EnterChatDTO",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/delivery.EnterChatDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/user/{uid}/leaveRoom/{chatroom_id}": {
            "get": {
                "description": "Leave a chatroom",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chatroom"
                ],
                "summary": "Leave chatroom",
                "operationId": "leave-chatroom",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "uid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Chatroom ID",
                        "name": "chatroom_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "delivery.DeleteChatDTO": {
            "type": "object",
            "properties": {
                "cid": {
                    "type": "integer"
                },
                "uid": {
                    "type": "integer"
                }
            }
        },
        "delivery.EnterChatDTO": {
            "type": "object",
            "properties": {
                "cid": {
                    "type": "integer"
                },
                "roomPassword": {
                    "type": "string"
                },
                "uid": {
                    "type": "integer"
                }
            }
        },
        "models.Chatroom": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "owner": {
                    "type": "integer"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "models.Response": {
            "type": "object",
            "properties": {
                "content": {},
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "chat",
	Description:      "pidorpidorasi",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
